name: Deploy Admin Panel to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'foreverAdmin/**'
      - '.github/workflows/deploy-admin.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Admin via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Connected to EC2!"
            echo "🚀 Updating Admin panel..."
            cd ~/Desktop/foreverAdmin
            git pull
            npm install
            npm run build
            echo "🔄 Reloading NGINX..."
            sudo systemctl reload nginx
            echo "✅ Admin deploy done!"
